### PR TITLE
Fix various issues

### PR DESCRIPTION
**Pull request by soyeonswife63**
BEAMinject is the only injector that is both FOSS and supports all Windows 10 Desktop platforms, including even the Surface RT
ModsCraft is simply necessary

### CODE REVIEW

**Comment by soyeonswife63** [comment]
@arsfrr Your political and religious beliefs should not affect an independent project. If the owner wants to keep it open, then let him

image

**Comment by arsfrr** [comment]
undid changes

**Comment by arsfrr** [comment]
pr closed now.

**Comment by soyeonswife63** [comment]
no commit credit is crazy

**Comment by arsfrr** [comment]
fixed.

**Pull request closed without merging**
